# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::PerformanceDataInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::PerformanceDataInputType`.

class Types::PerformanceDataInputType
  sig { returns(T.nilable(::Integer)) }
  def reps; end

  sig { returns(T.nilable(::Integer)) }
  def rpe; end

  sig { returns(T.nilable(::Integer)) }
  def sets; end

  sig { returns(T.nilable(::Integer)) }
  def weight; end
end
