# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::ReorderInstructionInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::ReorderInstructionInputType`.

class Types::ReorderInstructionInputType
  sig { returns(::Integer) }
  def exercise_history_id; end

  sig { returns(::Integer) }
  def new_order; end
end
