# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/addressable/all/addressable.rbi
#
# addressable-2.8.6

module Addressable
end
module Addressable::VERSION
end
module Addressable::IDNA
end
class Addressable::IDNA::PunycodeBadInput < StandardError
end
class Addressable::IDNA::PunycodeBigOutput < StandardError
end
class Addressable::IDNA::PunycodeOverflow < StandardError
end
class Addressable::URI
end
class Addressable::URI::InvalidURIError < StandardError
end
module Addressable::URI::CharacterClasses
end
module Addressable::URI::NormalizeCharacterClasses
end
module Addressable::URI::CharacterClassesRegexps
end
module Addressable::URI::NONE
end
class Addressable::Template
end
class Addressable::Template::InvalidTemplateValueError < StandardError
end
class Addressable::Template::InvalidTemplateOperatorError < StandardError
end
class Addressable::Template::TemplateOperatorAbortedError < StandardError
end
class Addressable::Template::MatchData
end
