# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/capybara/all/capybara.rbi
#
# capybara-3.39.2

module Capybara
end
class Capybara::SessionConfig
end
class Capybara::ReadOnlySessionConfig < SimpleDelegator
end
class Capybara::Config
  extend Forwardable
end
class Capybara::RegistrationContainer
end
module Capybara::Helpers
end
class Capybara::Helpers::Timer
end
module Capybara::SessionMatchers
end
class Capybara::Session
  include Capybara::SessionMatchers
end
class Capybara::Window
end
class Capybara::Server
end
class Capybara::Server::Middleware
end
class Capybara::Server::Middleware::Counter
end
class Capybara::Server::AnimationDisabler
end
class Capybara::Server::Checker
end
module XPath
end
class XPath::Renderer
end
module XPath::DSL
end
class Capybara::Selector < SimpleDelegator
end
module Capybara::Selector::Filters
end
class Capybara::Selector::Filters::Base
end
class Capybara::Selector::Filters::NodeFilter < Capybara::Selector::Filters::Base
end
class Capybara::Selector::Filters::ExpressionFilter < Capybara::Selector::Filters::Base
end
class Capybara::Selector::Filters::IdentityExpressionFilter < Capybara::Selector::Filters::ExpressionFilter
end
class Capybara::Selector::Filters::LocatorFilter < Capybara::Selector::Filters::NodeFilter
end
class Capybara::Selector::FilterSet
end
class Capybara::Selector::CSS
end
class Capybara::Selector::CSS::Splitter
end
class Capybara::Selector::RegexpDisassembler
end
class Capybara::Selector::RegexpDisassembler::Expression
end
class Capybara::Selector::XPathBuilder
end
class Capybara::Selector::CSSBuilder
end
class Capybara::Selector::Definition
  extend Forwardable
end
class Capybara::Result
  extend Forwardable
  include Enumerable
end
module Capybara::Queries
end
class Capybara::Queries::BaseQuery
end
class Capybara::Queries::SelectorQuery < Capybara::Queries::BaseQuery
end
class Capybara::Queries::SelectorQuery::Rectangle
end
class Capybara::Queries::TextQuery < Capybara::Queries::BaseQuery
end
class Capybara::Queries::TitleQuery < Capybara::Queries::BaseQuery
end
class Capybara::Queries::CurrentPathQuery < Capybara::Queries::BaseQuery
end
class Capybara::Queries::MatchQuery < Capybara::Queries::SelectorQuery
end
class Capybara::Queries::AncestorQuery < Capybara::Queries::SelectorQuery
end
class Capybara::Queries::SiblingQuery < Capybara::Queries::SelectorQuery
end
class Capybara::Queries::StyleQuery < Capybara::Queries::BaseQuery
end
class Capybara::Queries::ActiveElementQuery < Capybara::Queries::BaseQuery
end
module Capybara::Node
end
module Capybara::Node::Finders
end
module Capybara::Node::Matchers
end
module Capybara::Node::Actions
end
module Capybara::Node::DocumentMatchers
end
class Capybara::Node::Simple
  include Capybara::Node::DocumentMatchers
  include Capybara::Node::Finders
  include Capybara::Node::Matchers
end
class Capybara::Node::Base
  include Capybara::Node::Actions
  include Capybara::Node::Finders
  include Capybara::Node::Matchers
end
class Capybara::Node::Element < Capybara::Node::Base
end
class Capybara::Node::Document < Capybara::Node::Base
  include Capybara::Node::DocumentMatchers
end
class Capybara::Driver::Base
end
module Capybara::Driver
end
class Capybara::Driver::Node
end
class Capybara::RackTest::Driver < Capybara::Driver::Base
end
module Capybara::RackTest::Errors
end
class Capybara::RackTest::Errors::StaleElementReferenceError < StandardError
end
module Capybara::Node::WhitespaceNormalizer
end
class Capybara::RackTest::Node < Capybara::Driver::Node
  include Capybara::Node::WhitespaceNormalizer
end
class Capybara::RackTest::Form < Capybara::RackTest::Node
end
class Capybara::RackTest::Form::NilUploadedFile < Rack::Test::UploadedFile
end
class Capybara::RackTest::Form::ParamsHash < Hash
end
class Capybara::RackTest::Browser
  include Rack::Test::Methods
end
class Capybara::RackTest::CSSHandlers < BasicObject
  include Kernel
end
module Capybara::Selenium
end
module Capybara::Selenium::Find
end
module Capybara::Selenium::Scroll
end
class Capybara::Selenium::Node < Capybara::Driver::Node
  include Capybara::Node::WhitespaceNormalizer
  include Capybara::Selenium::Find
  include Capybara::Selenium::Scroll
end
class Capybara::Selenium::Node::SettableValue
end
class Capybara::Selenium::Node::ClickOptions
end
module Capybara::Selenium::Node::Html5Drag
end
module Capybara::Selenium::Node::FileInputClickEmulation
end
class Capybara::Selenium::ChromeNode < Capybara::Selenium::Node
  include Capybara::Selenium::Node::FileInputClickEmulation
  include Capybara::Selenium::Node::Html5Drag
end
module Capybara::Selenium::ChromeLogs
end
module Capybara::Selenium::Driver::ChromeDriver
end
class Capybara::Selenium::FirefoxNode < Capybara::Selenium::Node
  include Capybara::Selenium::Node::FileInputClickEmulation
  include Capybara::Selenium::Node::Html5Drag
end
module Capybara::Selenium::Driver::FirefoxDriver
end
module Capybara::Selenium::Driver::W3CFirefoxDriver
end
class Capybara::Selenium::IENode < Capybara::Selenium::Node
end
module Capybara::Selenium::Driver::InternetExplorerDriver
end
class Capybara::Selenium::Node::ModifierKeysStack
end
class Capybara::Selenium::SafariNode < Capybara::Selenium::Node
end
module Capybara::Selenium::Driver::SafariDriver
end
class Capybara::Selenium::EdgeNode < Capybara::Selenium::Node
  include Capybara::Selenium::Node::Html5Drag
end
module Capybara::Selenium::Driver::EdgeDriver
end
class Capybara::Selenium::Driver < Capybara::Driver::Base
  include Capybara::Selenium::Find
end
class Capybara::CapybaraError < StandardError
end
class Capybara::DriverNotFoundError < Capybara::CapybaraError
end
class Capybara::FrozenInTime < Capybara::CapybaraError
end
class Capybara::ElementNotFound < Capybara::CapybaraError
end
class Capybara::ModalNotFound < Capybara::CapybaraError
end
class Capybara::Ambiguous < Capybara::ElementNotFound
end
class Capybara::ExpectationNotMet < Capybara::ElementNotFound
end
class Capybara::FileNotFound < Capybara::CapybaraError
end
class Capybara::UnselectNotAllowed < Capybara::CapybaraError
end
class Capybara::NotSupportedByDriverError < Capybara::CapybaraError
end
class Capybara::InfiniteRedirectError < Capybara::CapybaraError
end
class Capybara::ScopeError < Capybara::CapybaraError
end
class Capybara::WindowError < Capybara::CapybaraError
end
class Capybara::ReadOnlyElementError < Capybara::CapybaraError
end
module Capybara::RackTest
end
