# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/drb/all/drb.rbi
#
# drb-2.2.0

module DRb
end
class DRb::DRbObject
end
class DRb::DRbServer
end
module DRb::DRbServer::InvokeMethod18Mixin
end
class DRb::DRbError < RuntimeError
end
class DRb::DRbConnError < DRb::DRbError
end
class DRb::DRbIdConv
end
module DRb::DRbUndumped
end
class DRb::DRbServerNotFound < DRb::DRbError
end
class DRb::DRbBadURI < DRb::DRbError
end
class DRb::DRbBadScheme < DRb::DRbError
end
class DRb::DRbUnknownError < DRb::DRbError
end
class DRb::DRbRemoteError < DRb::DRbError
end
class DRb::DRbUnknown
end
class DRb::DRbArray
end
class DRb::DRbMessage
end
module DRb::DRbProtocol
end
class DRb::DRbTCPSocket
end
class DRb::DRbURIOption
end
class DRb::ThreadObject
  include MonitorMixin
end
class DRb::DRbConn
end
class DRb::DRbServer::InvokeMethod
  include DRb::DRbServer::InvokeMethod18Mixin
end
class DRb::DRbUNIXSocket < DRb::DRbTCPSocket
end
