# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/public_suffix/all/public_suffix.rbi
#
# public_suffix-5.0.4

module PublicSuffix
end
class PublicSuffix::Domain
end
class PublicSuffix::Error < StandardError
end
class PublicSuffix::DomainInvalid < PublicSuffix::Error
end
class PublicSuffix::DomainNotAllowed < PublicSuffix::DomainInvalid
end
module PublicSuffix::Rule
end
class PublicSuffix::Rule::Base
end
class PublicSuffix::Rule::Normal < PublicSuffix::Rule::Base
end
class PublicSuffix::Rule::Wildcard < PublicSuffix::Rule::Base
end
class PublicSuffix::Rule::Exception < PublicSuffix::Rule::Base
end
class PublicSuffix::List
end
