# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rackup/all/rackup.rbi
#
# rackup-2.1.0

module Rackup
end
module Rackup::Handler
end
module Rack
end
class Rackup::Server
end
class Rackup::Server::Options
end
